### ISSUE TITLE
Selenide 5.3.+ doesn't run in container (creates driver locally)

### ISSUE THREAD

**Issue by daggerok** [selenide-examples/testcontainers#1]
Hello @asolntsev ,

Can you please verify if your tests are really running inside testcontainer (ie properly with remote selenium in docker)? 
I found in my case everything is working fine with selenide 5.2.x, but when I'm using newer selenide version, my browser start opening in local browser on my Mac, not inside testcontainer.

Thanks!

**Comment by asolntsev** [comment]
@daggerok Hi. I just tried: [our tests](https://github.com/selenide-examples/testcontainers/tree/master/src/test/java/org/selenide/examples) work well with Selenide 5.4.1 and 5.5.0. Both in IDEA and command-line (gradle). 

How exactly you configure Selenide to use browser inside docker? 
Is it possible that this code is execute AFTER you call `Selenide.open` or `Selenide.$` first time?

**Comment by daggerok** [comment]
Hey,

Here how you can reproduce:

* please clone [that](https://github.com/daggerok/testcontainers-selenide-example/) project
* uncomment [this line](https://github.com/daggerok/testcontainers-selenide-example/blob/master/build.gradle.kts#L59) in build.gradle.kts if you would like to test with gradle, or [that line](https://github.com/daggerok/testcontainers-selenide-example/blob/master/pom.xml#L22) in pom.xml file in case of maven...
* run tests with `./gradlew` or `./mvnw` commands

**Comment by asolntsev** [comment]
Thanks for the code, I I'll look at it.

**Comment by asolntsev** [comment]
@daggerok Sorry, I haven't investigated it in details, but probably the problem is that you call `close()` in the end of test. It closes the webdriver, and next time Selenide opens a new browser by itself. This time on local computer.

**Comment by daggerok** [comment]
Thanks, I will check

**Comment by daggerok** [comment]
Okay, I can confirm that after I moved out `Selenode.close()` in @AfterAll / @AfterClass:

```java
@AfterAll
  void afterAll() {
    // Warning: at this point if time Selenide will also stops Chrome remote WebDriver too...
    Selenide.close();
  }
```

It's working again.
Meanwhile if you for some reasons need open or close driver during tests, seems like still some migration is needed.

Thanks!

**Comment by asolntsev** [comment]
@daggerok Yes, it was mentioned in [Selenide 5.4.0 release notes](https://selenide.org/2019/10/16/selenide-5.4.0/):

> 2. Now method SelenideDriver.close() always closes the browser
